### ISSUE TITLE
using container in github action

### ISSUE THREAD

**Issue by PaulSt** [ameli/manylinux-cuda#2]
Hi there,

I've been using your container in github actions like so

```
jobs:
  maketest:
    runs-on: ubuntu-latest
    container:
      image: sameli/manylinux2014_x86_64_cuda_11
```

but recently I get the error 
`  failed to register layer: write /usr/local/cuda-11.7/targets/x86_64-linux/lib/libcusolver_static.a: no space left on device`

Do you know if there is any way to get the container up and running in a github action? 
did github shrink their disk space available..? 

Many thanks in advance :+1: 
Paul

**Comment by ameli** [comment]
Hi Paul, I resolve this by clearing runner's cache.

```
- name: Clear Cache
  run: rm -rf /opt/hostedtoolcache
```

**Comment by PaulSt** [comment]
Hi @ameli,
thank you for your answer! I am a bit lost, how do you run this in the same job, before loading a container?

**Comment by ameli** [comment]
Can you run the container as a step rather than a job? like

```
steps:

    - name: clean
      run: rm -rf /opt/hostedtoolcache
	
    - name: run container
      run: |
         docker pull sameli/manylinux2014_x86_64_cuda_11.7
         docker run -v $PWD:/workspace sameli/manylinux2014_x86_64_cuda_11.7 /bin/sh /workspace/scripts/inside_container.sh
```
